(define (make-segment p1 p2)
  (cons p1 p2))
(define (start-segment x)
  (car x))
(define (end-segment x)
  (cdr x))
(define (make-point x y)
  (cons x y))
(define (x-point x)
  (car x))
(define (y-point y)
  (cdr y))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))
(define (mid-point line)
  (define (average a b)
    (/ (+ a b) 2))
  (let ((mid-x (average
                (x-point (start-segment line))
                (x-point (end-segment line))))
        (mid-y (average
                (y-point (start-segment line))
                (y-point (end-segment line)))))
    (make-point mid-x mid-y)))
(print-point (mid-point (make-segment (make-point 2 2) (make-point 6 9))))
