(define (equal? a b)
  (cond ((or (and (null? a)
                  (not (null? b)))
             (and (null? b)
                  (not (null? a))))
         false)
        ((and (null? a)
              (null? b))
         true)
        ((and (eq? (car a) (car b))
              (equal? (cdr a) (cdr b)))
         true)
        (else
         false)))

